In [164]:
arr1 = torch.arange(1, 5)
arr2 = torch.arange(1, 10)
arr3 = torch.arange(1, 15)
arr_raw = [arr1, arr2, arr3]

# Padding
arr = torch.nn.utils.rnn.pad_sequence(arr_raw, batch_first=True)
mask = torch.where(arr==0, 1, 0) # If padding, then 1

# Packing
arr_len = [len(a) for a in arr_raw]
arr_pack = torch.nn.utils.rnn.pack_padded_sequence(arr, arr_len, batch_first=True, enforce_sorted=False)

# Unpacking
arr_unpack = torch.nn.utils.rnn.pad_packed_sequence(arr_pack, batch_first=True)

# Get last index
# last_idx = [torch.max(row) for row in mask]
last_idx = torch.argmax(mask, dim=-1)



print(arr_raw); print("_"*100)
print(mask); print("_"*100)
print(arr_pack); print("_"*100)
print(arr_unpack); print("_"*100)
print(last_idx)


[tensor([1, 2, 3, 4]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])]
____________________________________________________________________________________________________
tensor([[0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
____________________________________________________________________________________________________
PackedSequence(data=tensor([ 1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,  6,  6,  7,  7,
         8,  8,  9,  9, 10, 11, 12, 13, 14]), batch_sizes=tensor([3, 3, 3, 3, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1]), sorted_indices=tensor([2, 1, 0]), unsorted_indices=tensor([2, 1, 0]))
____________________________________________________________________________________________________
(tensor([[ 1,  2,  3,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9,  0,  0,  0,  0,  0],
 

In [239]:
import torch
import numpy as np

arr = [torch.Tensor([0,0,0,1,2,3]).unsqueeze(-1), torch.Tensor([4,5,6,7,8,9]).unsqueeze(-1)]
arr = torch.nn.utils.rnn.pad_sequence(arr, padding_value=0, batch_first=True)
arr = torch.nn.utils.rnn.pack_padded_sequence(arr, [3,6], batch_first=True, enforce_sorted=False)

model = torch.nn.LSTM(1, 3, batch_first=True)
output, _ = model(arr)
# output = arr

output, _ = torch.nn.utils.rnn.pad_packed_sequence(output, batch_first=True)
output

TypeError: expected Tensor as element 0 in argument 0, but got list

In [57]:
import torch

def calculate_lengths_left_padded(sequences, padding_value=0):
    lengths = []
    for seq in sequences:
        # Find the index of the first non-padding value
        first_non_pad = next((i for i, x in enumerate(seq) if x != padding_value), len(seq))
        lengths.append(len(seq) - first_non_pad)
    return lengths

# Example usage
sequences = torch.tensor([
    [0, 0, 1, 2, 3],  # Left-padded sequence
    [0, 0, 0, 4, 5]
])
lengths = calculate_lengths_left_padded(sequences)
print(lengths)
packed_sequences = torch.nn.utils.rnn.pack_padded_sequence(sequences, lengths, enforce_sorted=False)
torch.nn.utils.rnn.pad_packed_sequence(packed_sequences, batch_first=True)

[3, 2]


RuntimeError: shape '[1, 1]' is invalid for input of size 0

In [58]:
import torch

def calculate_lengths_left_padded(sequences, padding_value=0):
    lengths = []
    for seq in sequences:
        first_non_pad = next((i for i, x in enumerate(seq) if x != padding_value), len(seq))
        lengths.append(len(seq) - first_non_pad)
    return lengths

# Example usage
sequences = torch.tensor([
    [0, 0, 1, 2, 3],  # Left-padded sequence
    [0, 0, 0, 4, 5]
], dtype=torch.long)  # Ensure the correct data type

lengths = calculate_lengths_left_padded(sequences)
packed_sequences = torch.nn.utils.rnn.pack_padded_sequence(sequences, lengths, batch_first=True, enforce_sorted=False)
padded_output, output_lengths = torch.nn.utils.rnn.pad_packed_sequence(packed_sequences, batch_first=True)

print(padded_output)

tensor([[0, 0, 1],
        [0, 0, 0]])
